<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.10.2 on win32)" generated="20230227 19:02:25.091" rpa="false" schemaversion="2">
<suite id="s1" name="Search Data 03" source="C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\testcases\search_data_03.robot">
<test id="s1-t1" name="search data input date to infomation field">
<kw name="Open Store Accounting Website and go to home page" library="common_feature">
<arg>${user['username']}</arg>
<arg>${user['password']}</arg>
<arg>${module['store_audit']}</arg>
<arg>${menu['sam_6200']}</arg>
<doc>Open Store Accounting Website and go to home page</doc>
<msg timestamp="20230227 19:02:26.691" level="FAIL">Resolving variable '${user['username']}' failed: Variable '${user}' not found.</msg>
<status status="FAIL" starttime="20230227 19:02:26.675" endtime="20230227 19:02:26.691"/>
</kw>
<kw name="Clear data infomation field" library="home_feature">
<doc>Verify table infomation should be correct</doc>
<status status="NOT RUN" starttime="20230227 19:02:26.691" endtime="20230227 19:02:26.691"/>
</kw>
<kw name="Input date to" library="home_page">
<arg>${tc_01['date_to']}</arg>
<doc>Input date to</doc>
<status status="NOT RUN" starttime="20230227 19:02:26.691" endtime="20230227 19:02:26.691"/>
</kw>
<kw name="Click search button" library="home_page">
<doc>Click search button</doc>
<status status="NOT RUN" starttime="20230227 19:02:26.691" endtime="20230227 19:02:26.691"/>
</kw>
<kw name="Alert Should Be Present" library="SeleniumLibrary">
<arg>${message['date_alert']}</arg>
<arg>${message['accept']}</arg>
<doc>Verifies that an alert is present and by default, accepts it.</doc>
<status status="NOT RUN" starttime="20230227 19:02:26.691" endtime="20230227 19:02:26.691"/>
</kw>
<kw name="Close Store Accounting Website" library="common_keywords" type="TEARDOWN">
<doc>Close Store Accounting Website</doc>
<kw name="DobbyWebCommon.Default test teardown">
<msg timestamp="20230227 19:02:26.731" level="FAIL">No keyword with name 'DobbyWebCommon.Default test teardown' found.</msg>
<status status="FAIL" starttime="20230227 19:02:26.731" endtime="20230227 19:02:26.731"/>
</kw>
<kw name="DobbyWebCommon.Close all browsers and stop proxy server">
<msg timestamp="20230227 19:02:26.755" level="FAIL">No keyword with name 'DobbyWebCommon.Close all browsers and stop proxy server' found.</msg>
<status status="FAIL" starttime="20230227 19:02:26.755" endtime="20230227 19:02:26.755"/>
</kw>
<status status="FAIL" starttime="20230227 19:02:26.699" endtime="20230227 19:02:26.755">Several failures occurred:

1) No keyword with name 'DobbyWebCommon.Default test teardown' found.

2) No keyword with name 'DobbyWebCommon.Close all browsers and stop proxy server' found.</status>
</kw>
<doc>search data input date to infomation field</doc>
<tag>search_data</tag>
<status status="FAIL" starttime="20230227 19:02:26.675" endtime="20230227 19:02:26.755">Resolving variable '${user['username']}' failed: Variable '${user}' not found.

Also teardown failed:
Several failures occurred:

1) No keyword with name 'DobbyWebCommon.Default test teardown' found.

2) No keyword with name 'DobbyWebCommon.Close all browsers and stop proxy server' found.</status>
</test>
<status status="FAIL" starttime="20230227 19:02:25.099" endtime="20230227 19:02:26.763"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">search_data</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Search Data 03">Search Data 03</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230227 19:02:25.203" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 2: Importing library 'pabot.PabotLib' failed: ModuleNotFoundError: No module named 'pabot'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\natta\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\natta\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\natta\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib
  C:\Users\natta\AppData\Local\Programs\Python\Python310
  C:\Users\natta\AppData\Roaming\Python\Python310\site-packages
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230227 19:02:25.419" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 6: Importing library 'DebugLibrary' failed: ModuleNotFoundError: No module named 'DebugLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\natta\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\natta\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\natta\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib
  C:\Users\natta\AppData\Local\Programs\Python\Python310
  C:\Users\natta\AppData\Roaming\Python\Python310\site-packages
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230227 19:02:25.491" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 7: Importing library 'DobbyCommonLibrary' failed: ModuleNotFoundError: No module named 'DobbyCommonLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\natta\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\natta\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\natta\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib
  C:\Users\natta\AppData\Local\Programs\Python\Python310
  C:\Users\natta\AppData\Roaming\Python\Python310\site-packages
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\natta\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin</msg>
<msg timestamp="20230227 19:02:26.507" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 9: Resource file 'DobbyCommonLibrary\DobbyWebCommon.robot' does not exist.</msg>
<msg timestamp="20230227 19:02:26.515" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 10: Resource file 'DobbyCommonLibrary\DobbyCommon.robot' does not exist.</msg>
<msg timestamp="20230227 19:02:26.627" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 23: Processing variable file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\testdata\test_data.yaml' failed: Using YAML variable files requires PyYAML module to be installed. Typically you can install it by running `pip install pyyaml`.</msg>
<msg timestamp="20230227 19:02:26.659" level="ERROR">Error in file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\imports.robot' on line 25: Processing variable file 'C:\Users\natta\Desktop\gosoft_project-pim_store_accounting-main\gosoft_project-pim_store_accounting-main\resources\web\configs\env_local.yaml' failed: Using YAML variable files requires PyYAML module to be installed. Typically you can install it by running `pip install pyyaml`.</msg>
</errors>
</robot>
